baseURL: "https://mindscapes.wingster.cc/"
# baseURL: https://mindscapes.wingster.cc  # 绑定的域名
languageCode: zh-tw
title: MindScapes
theme: PaperMod # 主题名字，和themes文件夹下的一致

enableInlineShortcodes: true #允许内联短码
enableEmoji: true # 允许使用 Emoji 表情，建议 true
enableRobotsTXT: true # 允许爬虫抓取到搜索引擎，建议 true
hasCJKLanguage: true # 自动检测是否包含 中文日文韩文 如果文章中使用了很多中文引号的话可以开启
paginate: 8    # 每页显示的文章数

googleAnalytics: G-C33WZGBGNZ # 谷歌统计

#disqus
disqusShortname: mindscapes-w
disqus:
    enable: true
    shortname: mindscapes-w
    count: true

assets: 
  disableHLJS: true 
  favicon: "/static/favicon.ico" 
  favicon_dark: "/static/favicon_dark.png" 
  favicon16x16: "/static/favicon-16x16.png" 
  favicon32x32: "/static/favicon-32x32.png" 
  apple_touch_icon: "/static/apple-touch-icon.png" 
  safari_pinned_tab: "/static/safari-pinned-tab.svg" 

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema. 
  
  homeInfoParams:
    Title: MindScapes
    Content: >
      - 歡迎來到 Wingster 的部落格
      - **Mindscapes** 會記錄我的人生學習心得，以及分享興趣愛好
      - 若你想跟我交流想法，歡迎透過 Email ✉️ <wingsterlai@gmail.com> 與我聯繫

  socialIcons: # optional
        - name: "facebook"
          url: "https://www.facebook.com/wingsterlai"
        - name: "instagram"
          url: "https://www.instagram.com/wingsterlai/"
        - name: "medium"
          url: "https://medium.com/@wingster"
        - name: "email"
          url: "mailto:wingsterlai@gmail.com"
     
  cover:
    linkFullImages: true //點擊每個 post 的 cover image 會開啟新視窗並放大

  DateFormat: "2006-01-02"
  ShowReadingTime: true
  ShowWordCount: false
  ShowShareButtons: false
  ShowPostNavLinks: false
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: false
  ShowRssButtonInSectionTermList: true
  UseHugoToc: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  hidemeta: false # 是否隐藏文章的元信息，如发布日期、作者等
  hideSummary: false
  showtoc: true # 显示目录
  tocopen: true # 自动展开目录

menu:
  main:
    - identifier: categories
      name: Categories
      url: /categories/
      weight: 10
    - identifier: tags
      name: Tags
      url: /tags/
      weight: 20
    - identifier: archives
      name: Archives
      url: /archives/
      weight: 30





